[project]
name = "differential-geometry"
version = "0.1.0"
description = "Notes for discrete differential geometry."
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.9.4",
    "numpy>=2.0.2",
    "polyscope>=2.5.0",
    "scipy>=1.13.1",
]
